/**
 * GENERATED by scripts/gen-tokens.mjs — do not edit.
 * Typed public token names and the two resolved default appearances.
 */

export type MayTokenValue = string | number

export interface MayTokens {
  readonly alertGap: MayTokenValue
  readonly bgBase: MayTokenValue
  readonly bgElevated: MayTokenValue
  readonly bgGrouped: MayTokenValue
  readonly bgNested: MayTokenValue
  readonly blue: MayTokenValue
  readonly breakpointDesktop: MayTokenValue
  readonly brown: MayTokenValue
  readonly colorBg: MayTokenValue
  readonly colorDanger: MayTokenValue
  readonly colorDestructive: MayTokenValue
  readonly colorFill: MayTokenValue
  readonly colorFillQuaternary: MayTokenValue
  readonly colorFillSecondary: MayTokenValue
  readonly colorFillTertiary: MayTokenValue
  readonly colorHighlight: MayTokenValue
  readonly colorHighlightStrong: MayTokenValue
  readonly colorInfo: MayTokenValue
  readonly colorOnDestructive: MayTokenValue
  readonly colorOnPrimary: MayTokenValue
  readonly colorPrimary: MayTokenValue
  readonly colorRing: MayTokenValue
  readonly colorScrim: MayTokenValue
  readonly colorSeparator: MayTokenValue
  readonly colorSeparatorOpaque: MayTokenValue
  readonly colorSuccess: MayTokenValue
  readonly colorSurface: MayTokenValue
  readonly colorSurfaceNested: MayTokenValue
  readonly colorText: MayTokenValue
  readonly colorTextQuaternary: MayTokenValue
  readonly colorTextSecondary: MayTokenValue
  readonly colorTextTertiary: MayTokenValue
  readonly colorTint: MayTokenValue
  readonly colorWarning: MayTokenValue
  readonly controlH: MayTokenValue
  readonly controlHLg: MayTokenValue
  readonly controlHMd: MayTokenValue
  readonly controlHSm: MayTokenValue
  readonly controlHXs: MayTokenValue
  readonly cyan: MayTokenValue
  readonly fillPrimary: MayTokenValue
  readonly fillQuaternary: MayTokenValue
  readonly fillSecondary: MayTokenValue
  readonly fillTertiary: MayTokenValue
  readonly fontMono: MayTokenValue
  readonly fontRounded: MayTokenValue
  readonly fontSans: MayTokenValue
  readonly gradBlue: MayTokenValue
  readonly gradGray: MayTokenValue
  readonly gradGreen: MayTokenValue
  readonly gradIndigo: MayTokenValue
  readonly gradOrange: MayTokenValue
  readonly gradPink: MayTokenValue
  readonly gradPurple: MayTokenValue
  readonly gradRed: MayTokenValue
  readonly gradSpectrum: MayTokenValue
  readonly gradTeal: MayTokenValue
  readonly gradYellow: MayTokenValue
  readonly gray: MayTokenValue
  readonly gray2: MayTokenValue
  readonly gray3: MayTokenValue
  readonly gray4: MayTokenValue
  readonly gray5: MayTokenValue
  readonly gray6: MayTokenValue
  readonly green: MayTokenValue
  readonly hairline: MayTokenValue
  readonly indigo: MayTokenValue
  readonly insetBottom: MayTokenValue
  readonly insetLeft: MayTokenValue
  readonly insetRight: MayTokenValue
  readonly insetTop: MayTokenValue
  readonly keyboardInset: MayTokenValue
  readonly label: MayTokenValue
  readonly labelQuaternary: MayTokenValue
  readonly labelSecondary: MayTokenValue
  readonly labelTertiary: MayTokenValue
  readonly listLeadingW: MayTokenValue
  readonly mint: MayTokenValue
  readonly navBarSpace: MayTokenValue
  readonly navbarH: MayTokenValue
  readonly onColor: MayTokenValue
  readonly orange: MayTokenValue
  readonly pink: MayTokenValue
  readonly purple: MayTokenValue
  readonly radiusCard: MayTokenValue
  readonly radiusFull: MayTokenValue
  readonly radiusLg: MayTokenValue
  readonly radiusMd: MayTokenValue
  readonly radiusSheet: MayTokenValue
  readonly radiusSm: MayTokenValue
  readonly radiusSquircle: MayTokenValue
  readonly radiusXs: MayTokenValue
  readonly red: MayTokenValue
  readonly scrim: MayTokenValue
  readonly scrollbarSize: MayTokenValue
  readonly scrollbarThumb: MayTokenValue
  readonly scrollbarThumbHover: MayTokenValue
  readonly separator: MayTokenValue
  readonly separatorOpaque: MayTokenValue
  readonly shadow: MayTokenValue
  readonly shadow2xl: MayTokenValue
  readonly shadow2xs: MayTokenValue
  readonly shadowA1: MayTokenValue
  readonly shadowA2: MayTokenValue
  readonly shadowA3: MayTokenValue
  readonly shadowA4: MayTokenValue
  readonly shadowA5: MayTokenValue
  readonly shadowA6: MayTokenValue
  readonly shadowA7: MayTokenValue
  readonly shadowColor: MayTokenValue
  readonly shadowLg: MayTokenValue
  readonly shadowMd: MayTokenValue
  readonly shadowSm: MayTokenValue
  readonly shadowXl: MayTokenValue
  readonly shadowXs: MayTokenValue
  readonly space0: MayTokenValue
  readonly space1: MayTokenValue
  readonly space10: MayTokenValue
  readonly space12: MayTokenValue
  readonly space16: MayTokenValue
  readonly space2: MayTokenValue
  readonly space20: MayTokenValue
  readonly space24: MayTokenValue
  readonly space3: MayTokenValue
  readonly space4: MayTokenValue
  readonly space5: MayTokenValue
  readonly space6: MayTokenValue
  readonly space8: MayTokenValue
  readonly tabBarSpace: MayTokenValue
  readonly tabbarH: MayTokenValue
  readonly teal: MayTokenValue
  readonly textBody: MayTokenValue
  readonly textBodyLeading: MayTokenValue
  readonly textBodyTracking: MayTokenValue
  readonly textBodyWeight: MayTokenValue
  readonly textCallout: MayTokenValue
  readonly textCalloutLeading: MayTokenValue
  readonly textCalloutTracking: MayTokenValue
  readonly textCalloutWeight: MayTokenValue
  readonly textCaption1: MayTokenValue
  readonly textCaption1Leading: MayTokenValue
  readonly textCaption1Tracking: MayTokenValue
  readonly textCaption1Weight: MayTokenValue
  readonly textCaption2: MayTokenValue
  readonly textCaption2Leading: MayTokenValue
  readonly textCaption2Tracking: MayTokenValue
  readonly textCaption2Weight: MayTokenValue
  readonly textFootnote: MayTokenValue
  readonly textFootnoteLeading: MayTokenValue
  readonly textFootnoteTracking: MayTokenValue
  readonly textFootnoteWeight: MayTokenValue
  readonly textHeadline: MayTokenValue
  readonly textHeadlineLeading: MayTokenValue
  readonly textHeadlineTracking: MayTokenValue
  readonly textHeadlineWeight: MayTokenValue
  readonly textLargeTitle: MayTokenValue
  readonly textLargeTitleLeading: MayTokenValue
  readonly textLargeTitleTracking: MayTokenValue
  readonly textLargeTitleWeight: MayTokenValue
  readonly textSubheadline: MayTokenValue
  readonly textSubheadlineLeading: MayTokenValue
  readonly textSubheadlineTracking: MayTokenValue
  readonly textSubheadlineWeight: MayTokenValue
  readonly textTitle1: MayTokenValue
  readonly textTitle1Leading: MayTokenValue
  readonly textTitle1Tracking: MayTokenValue
  readonly textTitle1Weight: MayTokenValue
  readonly textTitle2: MayTokenValue
  readonly textTitle2Leading: MayTokenValue
  readonly textTitle2Tracking: MayTokenValue
  readonly textTitle2Weight: MayTokenValue
  readonly textTitle3: MayTokenValue
  readonly textTitle3Leading: MayTokenValue
  readonly textTitle3Tracking: MayTokenValue
  readonly textTitle3Weight: MayTokenValue
  readonly yellow: MayTokenValue
  readonly zBase: MayTokenValue
  readonly zNav: MayTokenValue
  readonly zOverlay: MayTokenValue
  readonly zPopover: MayTokenValue
  readonly zSheet: MayTokenValue
  readonly zSticky: MayTokenValue
  readonly zToast: MayTokenValue
  readonly zTooltip: MayTokenValue
}

export const mayTokenCssNames = {
  alertGap: 'alert-gap',
  bgBase: 'bg-base',
  bgElevated: 'bg-elevated',
  bgGrouped: 'bg-grouped',
  bgNested: 'bg-nested',
  blue: 'blue',
  breakpointDesktop: 'breakpoint-desktop',
  brown: 'brown',
  colorBg: 'color-bg',
  colorDanger: 'color-danger',
  colorDestructive: 'color-destructive',
  colorFill: 'color-fill',
  colorFillQuaternary: 'color-fill-quaternary',
  colorFillSecondary: 'color-fill-secondary',
  colorFillTertiary: 'color-fill-tertiary',
  colorHighlight: 'color-highlight',
  colorHighlightStrong: 'color-highlight-strong',
  colorInfo: 'color-info',
  colorOnDestructive: 'color-on-destructive',
  colorOnPrimary: 'color-on-primary',
  colorPrimary: 'color-primary',
  colorRing: 'color-ring',
  colorScrim: 'color-scrim',
  colorSeparator: 'color-separator',
  colorSeparatorOpaque: 'color-separator-opaque',
  colorSuccess: 'color-success',
  colorSurface: 'color-surface',
  colorSurfaceNested: 'color-surface-nested',
  colorText: 'color-text',
  colorTextQuaternary: 'color-text-quaternary',
  colorTextSecondary: 'color-text-secondary',
  colorTextTertiary: 'color-text-tertiary',
  colorTint: 'color-tint',
  colorWarning: 'color-warning',
  controlH: 'control-h',
  controlHLg: 'control-h-lg',
  controlHMd: 'control-h-md',
  controlHSm: 'control-h-sm',
  controlHXs: 'control-h-xs',
  cyan: 'cyan',
  fillPrimary: 'fill-primary',
  fillQuaternary: 'fill-quaternary',
  fillSecondary: 'fill-secondary',
  fillTertiary: 'fill-tertiary',
  fontMono: 'font-mono',
  fontRounded: 'font-rounded',
  fontSans: 'font-sans',
  gradBlue: 'grad-blue',
  gradGray: 'grad-gray',
  gradGreen: 'grad-green',
  gradIndigo: 'grad-indigo',
  gradOrange: 'grad-orange',
  gradPink: 'grad-pink',
  gradPurple: 'grad-purple',
  gradRed: 'grad-red',
  gradSpectrum: 'grad-spectrum',
  gradTeal: 'grad-teal',
  gradYellow: 'grad-yellow',
  gray: 'gray',
  gray2: 'gray-2',
  gray3: 'gray-3',
  gray4: 'gray-4',
  gray5: 'gray-5',
  gray6: 'gray-6',
  green: 'green',
  hairline: 'hairline',
  indigo: 'indigo',
  insetBottom: 'inset-bottom',
  insetLeft: 'inset-left',
  insetRight: 'inset-right',
  insetTop: 'inset-top',
  keyboardInset: 'keyboard-inset',
  label: 'label',
  labelQuaternary: 'label-quaternary',
  labelSecondary: 'label-secondary',
  labelTertiary: 'label-tertiary',
  listLeadingW: 'list-leading-w',
  mint: 'mint',
  navBarSpace: 'nav-bar-space',
  navbarH: 'navbar-h',
  onColor: 'on-color',
  orange: 'orange',
  pink: 'pink',
  purple: 'purple',
  radiusCard: 'radius-card',
  radiusFull: 'radius-full',
  radiusLg: 'radius-lg',
  radiusMd: 'radius-md',
  radiusSheet: 'radius-sheet',
  radiusSm: 'radius-sm',
  radiusSquircle: 'radius-squircle',
  radiusXs: 'radius-xs',
  red: 'red',
  scrim: 'scrim',
  scrollbarSize: 'scrollbar-size',
  scrollbarThumb: 'scrollbar-thumb',
  scrollbarThumbHover: 'scrollbar-thumb-hover',
  separator: 'separator',
  separatorOpaque: 'separator-opaque',
  shadow: 'shadow',
  shadow2xl: 'shadow-2xl',
  shadow2xs: 'shadow-2xs',
  shadowA1: 'shadow-a1',
  shadowA2: 'shadow-a2',
  shadowA3: 'shadow-a3',
  shadowA4: 'shadow-a4',
  shadowA5: 'shadow-a5',
  shadowA6: 'shadow-a6',
  shadowA7: 'shadow-a7',
  shadowColor: 'shadow-color',
  shadowLg: 'shadow-lg',
  shadowMd: 'shadow-md',
  shadowSm: 'shadow-sm',
  shadowXl: 'shadow-xl',
  shadowXs: 'shadow-xs',
  space0: 'space-0',
  space1: 'space-1',
  space10: 'space-10',
  space12: 'space-12',
  space16: 'space-16',
  space2: 'space-2',
  space20: 'space-20',
  space24: 'space-24',
  space3: 'space-3',
  space4: 'space-4',
  space5: 'space-5',
  space6: 'space-6',
  space8: 'space-8',
  tabBarSpace: 'tab-bar-space',
  tabbarH: 'tabbar-h',
  teal: 'teal',
  textBody: 'text-body',
  textBodyLeading: 'text-body-leading',
  textBodyTracking: 'text-body-tracking',
  textBodyWeight: 'text-body-weight',
  textCallout: 'text-callout',
  textCalloutLeading: 'text-callout-leading',
  textCalloutTracking: 'text-callout-tracking',
  textCalloutWeight: 'text-callout-weight',
  textCaption1: 'text-caption-1',
  textCaption1Leading: 'text-caption-1-leading',
  textCaption1Tracking: 'text-caption-1-tracking',
  textCaption1Weight: 'text-caption-1-weight',
  textCaption2: 'text-caption-2',
  textCaption2Leading: 'text-caption-2-leading',
  textCaption2Tracking: 'text-caption-2-tracking',
  textCaption2Weight: 'text-caption-2-weight',
  textFootnote: 'text-footnote',
  textFootnoteLeading: 'text-footnote-leading',
  textFootnoteTracking: 'text-footnote-tracking',
  textFootnoteWeight: 'text-footnote-weight',
  textHeadline: 'text-headline',
  textHeadlineLeading: 'text-headline-leading',
  textHeadlineTracking: 'text-headline-tracking',
  textHeadlineWeight: 'text-headline-weight',
  textLargeTitle: 'text-large-title',
  textLargeTitleLeading: 'text-large-title-leading',
  textLargeTitleTracking: 'text-large-title-tracking',
  textLargeTitleWeight: 'text-large-title-weight',
  textSubheadline: 'text-subheadline',
  textSubheadlineLeading: 'text-subheadline-leading',
  textSubheadlineTracking: 'text-subheadline-tracking',
  textSubheadlineWeight: 'text-subheadline-weight',
  textTitle1: 'text-title-1',
  textTitle1Leading: 'text-title-1-leading',
  textTitle1Tracking: 'text-title-1-tracking',
  textTitle1Weight: 'text-title-1-weight',
  textTitle2: 'text-title-2',
  textTitle2Leading: 'text-title-2-leading',
  textTitle2Tracking: 'text-title-2-tracking',
  textTitle2Weight: 'text-title-2-weight',
  textTitle3: 'text-title-3',
  textTitle3Leading: 'text-title-3-leading',
  textTitle3Tracking: 'text-title-3-tracking',
  textTitle3Weight: 'text-title-3-weight',
  yellow: 'yellow',
  zBase: 'z-base',
  zNav: 'z-nav',
  zOverlay: 'z-overlay',
  zPopover: 'z-popover',
  zSheet: 'z-sheet',
  zSticky: 'z-sticky',
  zToast: 'z-toast',
  zTooltip: 'z-tooltip',
} as const satisfies Record<keyof MayTokens, string>

export const mayLightTokens = {
  alertGap: "0px",
  bgBase: "#ffffff",
  bgElevated: "#ffffff",
  bgGrouped: "#f2f2f7",
  bgNested: "#f2f2f7",
  blue: "#007aff",
  breakpointDesktop: "1024px",
  brown: "#a2845e",
  colorBg: "var(--may-bg-grouped)",
  colorDanger: "var(--may-red)",
  colorDestructive: "var(--may-red)",
  colorFill: "var(--may-fill-primary)",
  colorFillQuaternary: "var(--may-fill-quaternary)",
  colorFillSecondary: "var(--may-fill-secondary)",
  colorFillTertiary: "var(--may-fill-tertiary)",
  colorHighlight: "var(--may-fill-quaternary)",
  colorHighlightStrong: "var(--may-fill-tertiary)",
  colorInfo: "var(--may-blue)",
  colorOnDestructive: "var(--may-on-color)",
  colorOnPrimary: "var(--may-on-color)",
  colorPrimary: "var(--may-blue)",
  colorRing: "var(--may-color-tint)",
  colorScrim: "var(--may-scrim)",
  colorSeparator: "var(--may-separator)",
  colorSeparatorOpaque: "var(--may-separator-opaque)",
  colorSuccess: "var(--may-green)",
  colorSurface: "var(--may-bg-elevated)",
  colorSurfaceNested: "var(--may-bg-nested)",
  colorText: "var(--may-label)",
  colorTextQuaternary: "var(--may-label-quaternary)",
  colorTextSecondary: "var(--may-label-secondary)",
  colorTextTertiary: "var(--may-label-tertiary)",
  colorTint: "var(--may-blue)",
  colorWarning: "var(--may-orange)",
  controlH: "2.75rem",
  controlHLg: "calc(var(--may-control-h) + 0.5rem)",
  controlHMd: "var(--may-control-h)",
  controlHSm: "calc(var(--may-control-h) - 0.5rem)",
  controlHXs: "calc(var(--may-control-h) - 0.75rem)",
  cyan: "#32ade6",
  fillPrimary: "rgba(120, 120, 128, 0.2)",
  fillQuaternary: "rgba(116, 116, 128, 0.08)",
  fillSecondary: "rgba(120, 120, 128, 0.16)",
  fillTertiary: "rgba(118, 118, 128, 0.12)",
  fontMono: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, monospace",
  fontRounded: "ui-rounded, var(--may-font-sans)",
  fontSans: "-apple-system, BlinkMacSystemFont, system-ui, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  gradBlue: "linear-gradient(180deg, #64b5ff 0%, #007aff 52%, #005ecb 100%)",
  gradGray: "linear-gradient(180deg, #b8b8bd 0%, #8e8e93 52%, #6d6d72 100%)",
  gradGreen: "linear-gradient(180deg, #5fe07a 0%, #34c759 52%, #28a745 100%)",
  gradIndigo: "linear-gradient(180deg, #8b8ae8 0%, #5856d6 52%, #4442b5 100%)",
  gradOrange: "linear-gradient(180deg, #ffb340 0%, #ff9500 52%, #d97e00 100%)",
  gradPink: "linear-gradient(180deg, #ff6b8a 0%, #ff2d55 52%, #d92546 100%)",
  gradPurple: "linear-gradient(180deg, #cd8ae8 0%, #af52de 52%, #9040ba 100%)",
  gradRed: "linear-gradient(180deg, #ff6b63 0%, #ff3b30 52%, #d92b20 100%)",
  gradSpectrum: "linear-gradient(135deg, #ff2d55 0%, #ff9500 28%, #ffcc00 52%, #34c759 72%, #007aff 100%)",
  gradTeal: "linear-gradient(180deg, #6fd0e0 0%, #30b0c7 52%, #2894a8 100%)",
  gradYellow: "linear-gradient(180deg, #ffe066 0%, #ffcc00 52%, #d9ad00 100%)",
  gray: "#8e8e93",
  gray2: "#aeaeb2",
  gray3: "#c7c7cc",
  gray4: "#d1d1d6",
  gray5: "#e5e5ea",
  gray6: "#f2f2f7",
  green: "#34c759",
  hairline: "0.5px",
  indigo: "#5856d6",
  insetBottom: "env(safe-area-inset-bottom, 0px)",
  insetLeft: "env(safe-area-inset-left, 0px)",
  insetRight: "env(safe-area-inset-right, 0px)",
  insetTop: "env(safe-area-inset-top, 0px)",
  keyboardInset: "0px",
  label: "#000000",
  labelQuaternary: "rgba(60, 60, 67, 0.18)",
  labelSecondary: "rgba(60, 60, 67, 0.6)",
  labelTertiary: "rgba(60, 60, 67, 0.3)",
  listLeadingW: "29px",
  mint: "#00c7be",
  navBarSpace: "calc(var(--may-navbar-h) + var(--may-inset-top))",
  navbarH: "2.75rem",
  onColor: "#ffffff",
  orange: "#ff9500",
  pink: "#ff2d55",
  purple: "#af52de",
  radiusCard: "16px",
  radiusFull: "9999px",
  radiusLg: "12px",
  radiusMd: "10px",
  radiusSheet: "20px",
  radiusSm: "8px",
  radiusSquircle: "22%",
  radiusXs: "6px",
  red: "#ff3b30",
  scrim: "rgba(0, 0, 0, 0.4)",
  scrollbarSize: "8px",
  scrollbarThumb: "rgba(60, 60, 67, 0.28)",
  scrollbarThumbHover: "rgba(60, 60, 67, 0.42)",
  separator: "rgba(60, 60, 67, 0.29)",
  separatorOpaque: "#c6c6c8",
  shadow: "0 2px 6px -1px rgba(var(--may-shadow-color), var(--may-shadow-a3))",
  shadow2xl: "0 28px 64px -14px rgba(var(--may-shadow-color), var(--may-shadow-a7))",
  shadow2xs: "0 1px 1px 0 rgba(var(--may-shadow-color), var(--may-shadow-a1))",
  shadowA1: "0.03",
  shadowA2: "0.04",
  shadowA3: "0.06",
  shadowA4: "0.08",
  shadowA5: "0.12",
  shadowA6: "0.16",
  shadowA7: "0.2",
  shadowColor: "0, 0, 0",
  shadowLg: "0 12px 32px -6px rgba(var(--may-shadow-color), var(--may-shadow-a5))",
  shadowMd: "0 4px 12px -2px rgba(var(--may-shadow-color), var(--may-shadow-a4))",
  shadowSm: "0 1px 2px 0 rgba(var(--may-shadow-color), var(--may-shadow-a2))",
  shadowXl: "0 20px 48px -10px rgba(var(--may-shadow-color), var(--may-shadow-a6))",
  shadowXs: "0 1px 2px 0 rgba(var(--may-shadow-color), var(--may-shadow-a2))",
  space0: "0",
  space1: "0.25rem",
  space10: "2.5rem",
  space12: "3rem",
  space16: "4rem",
  space2: "0.5rem",
  space20: "5rem",
  space24: "6rem",
  space3: "0.75rem",
  space4: "1rem",
  space5: "1.25rem",
  space6: "1.5rem",
  space8: "2rem",
  tabBarSpace: "calc( var(--may-tabbar-h) + var(--may-inset-bottom) + var(--may-space-4) * 2 )",
  tabbarH: "3.25rem",
  teal: "#30b0c7",
  textBody: "1.0625rem",
  textBodyLeading: "1.375rem",
  textBodyTracking: "-0.002em",
  textBodyWeight: "400",
  textCallout: "1rem",
  textCalloutLeading: "1.3125rem",
  textCalloutTracking: "0em",
  textCalloutWeight: "400",
  textCaption1: "0.75rem",
  textCaption1Leading: "1rem",
  textCaption1Tracking: "0.005em",
  textCaption1Weight: "400",
  textCaption2: "0.6875rem",
  textCaption2Leading: "0.8125rem",
  textCaption2Tracking: "0.006em",
  textCaption2Weight: "400",
  textFootnote: "0.8125rem",
  textFootnoteLeading: "1.125rem",
  textFootnoteTracking: "0em",
  textFootnoteWeight: "400",
  textHeadline: "1.0625rem",
  textHeadlineLeading: "1.375rem",
  textHeadlineTracking: "-0.006em",
  textHeadlineWeight: "600",
  textLargeTitle: "2.125rem",
  textLargeTitleLeading: "2.5625rem",
  textLargeTitleTracking: "-0.02em",
  textLargeTitleWeight: "700",
  textSubheadline: "0.9375rem",
  textSubheadlineLeading: "1.25rem",
  textSubheadlineTracking: "0em",
  textSubheadlineWeight: "400",
  textTitle1: "1.75rem",
  textTitle1Leading: "2.125rem",
  textTitle1Tracking: "-0.016em",
  textTitle1Weight: "700",
  textTitle2: "1.375rem",
  textTitle2Leading: "1.75rem",
  textTitle2Tracking: "-0.012em",
  textTitle2Weight: "700",
  textTitle3: "1.25rem",
  textTitle3Leading: "1.5625rem",
  textTitle3Tracking: "-0.01em",
  textTitle3Weight: "600",
  yellow: "#ffcc00",
  zBase: "1",
  zNav: "200",
  zOverlay: "1000",
  zPopover: "1200",
  zSheet: "1100",
  zSticky: "100",
  zToast: "1300",
  zTooltip: "1400",
} as const satisfies Readonly<MayTokens>

export const mayDarkTokens = {
  alertGap: "0px",
  bgBase: "#000000",
  bgElevated: "#1c1c1e",
  bgGrouped: "#000000",
  bgNested: "#2c2c2e",
  blue: "#0a84ff",
  breakpointDesktop: "1024px",
  brown: "#ac8e68",
  colorBg: "var(--may-bg-grouped)",
  colorDanger: "var(--may-red)",
  colorDestructive: "var(--may-red)",
  colorFill: "var(--may-fill-primary)",
  colorFillQuaternary: "var(--may-fill-quaternary)",
  colorFillSecondary: "var(--may-fill-secondary)",
  colorFillTertiary: "var(--may-fill-tertiary)",
  colorHighlight: "var(--may-fill-quaternary)",
  colorHighlightStrong: "var(--may-fill-tertiary)",
  colorInfo: "var(--may-blue)",
  colorOnDestructive: "var(--may-on-color)",
  colorOnPrimary: "var(--may-on-color)",
  colorPrimary: "var(--may-blue)",
  colorRing: "var(--may-color-tint)",
  colorScrim: "var(--may-scrim)",
  colorSeparator: "var(--may-separator)",
  colorSeparatorOpaque: "var(--may-separator-opaque)",
  colorSuccess: "var(--may-green)",
  colorSurface: "var(--may-bg-elevated)",
  colorSurfaceNested: "var(--may-bg-nested)",
  colorText: "var(--may-label)",
  colorTextQuaternary: "var(--may-label-quaternary)",
  colorTextSecondary: "var(--may-label-secondary)",
  colorTextTertiary: "var(--may-label-tertiary)",
  colorTint: "var(--may-blue)",
  colorWarning: "var(--may-orange)",
  controlH: "2.75rem",
  controlHLg: "calc(var(--may-control-h) + 0.5rem)",
  controlHMd: "var(--may-control-h)",
  controlHSm: "calc(var(--may-control-h) - 0.5rem)",
  controlHXs: "calc(var(--may-control-h) - 0.75rem)",
  cyan: "#64d2ff",
  fillPrimary: "rgba(120, 120, 128, 0.36)",
  fillQuaternary: "rgba(116, 116, 128, 0.18)",
  fillSecondary: "rgba(120, 120, 128, 0.32)",
  fillTertiary: "rgba(118, 118, 128, 0.24)",
  fontMono: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, monospace",
  fontRounded: "ui-rounded, var(--may-font-sans)",
  fontSans: "-apple-system, BlinkMacSystemFont, system-ui, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  gradBlue: "linear-gradient(180deg, #64b5ff 0%, #007aff 52%, #005ecb 100%)",
  gradGray: "linear-gradient(180deg, #b8b8bd 0%, #8e8e93 52%, #6d6d72 100%)",
  gradGreen: "linear-gradient(180deg, #5fe07a 0%, #34c759 52%, #28a745 100%)",
  gradIndigo: "linear-gradient(180deg, #8b8ae8 0%, #5856d6 52%, #4442b5 100%)",
  gradOrange: "linear-gradient(180deg, #ffb340 0%, #ff9500 52%, #d97e00 100%)",
  gradPink: "linear-gradient(180deg, #ff6b8a 0%, #ff2d55 52%, #d92546 100%)",
  gradPurple: "linear-gradient(180deg, #cd8ae8 0%, #af52de 52%, #9040ba 100%)",
  gradRed: "linear-gradient(180deg, #ff6b63 0%, #ff3b30 52%, #d92b20 100%)",
  gradSpectrum: "linear-gradient(135deg, #ff2d55 0%, #ff9500 28%, #ffcc00 52%, #34c759 72%, #007aff 100%)",
  gradTeal: "linear-gradient(180deg, #6fd0e0 0%, #30b0c7 52%, #2894a8 100%)",
  gradYellow: "linear-gradient(180deg, #ffe066 0%, #ffcc00 52%, #d9ad00 100%)",
  gray: "#8e8e93",
  gray2: "#636366",
  gray3: "#48484a",
  gray4: "#3a3a3c",
  gray5: "#2c2c2e",
  gray6: "#1c1c1e",
  green: "#30d158",
  hairline: "0.5px",
  indigo: "#5e5ce6",
  insetBottom: "env(safe-area-inset-bottom, 0px)",
  insetLeft: "env(safe-area-inset-left, 0px)",
  insetRight: "env(safe-area-inset-right, 0px)",
  insetTop: "env(safe-area-inset-top, 0px)",
  keyboardInset: "0px",
  label: "#ffffff",
  labelQuaternary: "rgba(235, 235, 245, 0.16)",
  labelSecondary: "rgba(235, 235, 245, 0.6)",
  labelTertiary: "rgba(235, 235, 245, 0.3)",
  listLeadingW: "29px",
  mint: "#63e6e2",
  navBarSpace: "calc(var(--may-navbar-h) + var(--may-inset-top))",
  navbarH: "2.75rem",
  onColor: "#ffffff",
  orange: "#ff9f0a",
  pink: "#ff375f",
  purple: "#bf5af2",
  radiusCard: "16px",
  radiusFull: "9999px",
  radiusLg: "12px",
  radiusMd: "10px",
  radiusSheet: "20px",
  radiusSm: "8px",
  radiusSquircle: "22%",
  radiusXs: "6px",
  red: "#ff453a",
  scrim: "rgba(0, 0, 0, 0.55)",
  scrollbarSize: "8px",
  scrollbarThumb: "rgba(235, 235, 245, 0.28)",
  scrollbarThumbHover: "rgba(235, 235, 245, 0.42)",
  separator: "rgba(84, 84, 88, 0.6)",
  separatorOpaque: "#38383a",
  shadow: "0 2px 6px -1px rgba(var(--may-shadow-color), var(--may-shadow-a3))",
  shadow2xl: "0 28px 64px -14px rgba(var(--may-shadow-color), var(--may-shadow-a7))",
  shadow2xs: "0 1px 1px 0 rgba(var(--may-shadow-color), var(--may-shadow-a1))",
  shadowA1: "0.2",
  shadowA2: "0.24",
  shadowA3: "0.32",
  shadowA4: "0.4",
  shadowA5: "0.48",
  shadowA6: "0.56",
  shadowA7: "0.64",
  shadowColor: "0, 0, 0",
  shadowLg: "0 12px 32px -6px rgba(var(--may-shadow-color), var(--may-shadow-a5))",
  shadowMd: "0 4px 12px -2px rgba(var(--may-shadow-color), var(--may-shadow-a4))",
  shadowSm: "0 1px 2px 0 rgba(var(--may-shadow-color), var(--may-shadow-a2))",
  shadowXl: "0 20px 48px -10px rgba(var(--may-shadow-color), var(--may-shadow-a6))",
  shadowXs: "0 1px 2px 0 rgba(var(--may-shadow-color), var(--may-shadow-a2))",
  space0: "0",
  space1: "0.25rem",
  space10: "2.5rem",
  space12: "3rem",
  space16: "4rem",
  space2: "0.5rem",
  space20: "5rem",
  space24: "6rem",
  space3: "0.75rem",
  space4: "1rem",
  space5: "1.25rem",
  space6: "1.5rem",
  space8: "2rem",
  tabBarSpace: "calc( var(--may-tabbar-h) + var(--may-inset-bottom) + var(--may-space-4) * 2 )",
  tabbarH: "3.25rem",
  teal: "#40c8e0",
  textBody: "1.0625rem",
  textBodyLeading: "1.375rem",
  textBodyTracking: "-0.002em",
  textBodyWeight: "400",
  textCallout: "1rem",
  textCalloutLeading: "1.3125rem",
  textCalloutTracking: "0em",
  textCalloutWeight: "400",
  textCaption1: "0.75rem",
  textCaption1Leading: "1rem",
  textCaption1Tracking: "0.005em",
  textCaption1Weight: "400",
  textCaption2: "0.6875rem",
  textCaption2Leading: "0.8125rem",
  textCaption2Tracking: "0.006em",
  textCaption2Weight: "400",
  textFootnote: "0.8125rem",
  textFootnoteLeading: "1.125rem",
  textFootnoteTracking: "0em",
  textFootnoteWeight: "400",
  textHeadline: "1.0625rem",
  textHeadlineLeading: "1.375rem",
  textHeadlineTracking: "-0.006em",
  textHeadlineWeight: "600",
  textLargeTitle: "2.125rem",
  textLargeTitleLeading: "2.5625rem",
  textLargeTitleTracking: "-0.02em",
  textLargeTitleWeight: "700",
  textSubheadline: "0.9375rem",
  textSubheadlineLeading: "1.25rem",
  textSubheadlineTracking: "0em",
  textSubheadlineWeight: "400",
  textTitle1: "1.75rem",
  textTitle1Leading: "2.125rem",
  textTitle1Tracking: "-0.016em",
  textTitle1Weight: "700",
  textTitle2: "1.375rem",
  textTitle2Leading: "1.75rem",
  textTitle2Tracking: "-0.012em",
  textTitle2Weight: "700",
  textTitle3: "1.25rem",
  textTitle3Leading: "1.5625rem",
  textTitle3Tracking: "-0.01em",
  textTitle3Weight: "600",
  yellow: "#ffd60a",
  zBase: "1",
  zNav: "200",
  zOverlay: "1000",
  zPopover: "1200",
  zSheet: "1100",
  zSticky: "100",
  zToast: "1300",
  zTooltip: "1400",
} as const satisfies Readonly<MayTokens>
