/**
 * Generates May UI's motion curve tokens.
 *
 * A CSS `linear()` easing encodes an arbitrary curve as sampled points, which
 * means a real spring — overshoot, settle and all — can run as an ordinary CSS
 * transition on the compositor, with no JavaScript on the animation frame and
 * nothing shipped to the browser. This script does the sampling at build time
 * and writes the result out as custom properties.
 *
 * Two sources feed it:
 *   1. A damped harmonic oscillator, for physically-derived springs.
 *   2. easing-utils, for the named expressive curves (back / elastic / bounce).
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import * as easings from 'easing-utils'

const here = dirname(fileURLToPath(import.meta.url))

/** Round hard: every wasted digit is bytes in every consumer's stylesheet. */
const r = (n) => Number(n.toFixed(4))

/**
 * Simulate a damped spring and return {points, durationMs}.
 * Integrates until the mass has settled inside `rest` for a few frames, so the
 * duration is derived from the physics rather than guessed.
 */
function simulateSpring({ stiffness, damping, mass = 1, rest = 0.004 }) {
  const dt = 1 / 240
  let x = -1
  let v = 0
  let t = 0
  let settledFor = 0
  const raw = []

  while (t < 6) {
    const a = (-stiffness * x - damping * v) / mass
    v += a * dt
    x += v * dt
    t += dt
    raw.push({ t, value: 1 + x })
    if (Math.abs(x) < rest && Math.abs(v) < rest) {
      settledFor += dt
      if (settledFor > 0.03) break
    } else {
      settledFor = 0
    }
  }

  const durationMs = Math.round(t * 1000)
  return { raw, durationMs }
}

/** Resample an arbitrary (t → value) series onto N evenly spaced stops. */
function resample(raw, steps) {
  const total = raw[raw.length - 1].t
  const out = []
  for (let i = 0; i <= steps; i++) {
    const target = (i / steps) * total
    let lo = 0
    while (lo < raw.length - 1 && raw[lo].t < target) lo++
    out.push(r(raw[lo].value))
  }
  out[0] = 0
  out[out.length - 1] = 1
  return out
}

/** Drop interior points that a linear interpolation of their neighbours already predicts. */
function prune(points, tolerance = 0.0035) {
  const keep = [points[0]]
  for (let i = 1; i < points.length - 1; i++) {
    const predicted = (keep[keep.length - 1] + points[i + 1]) / 2
    if (Math.abs(points[i] - predicted) > tolerance) keep.push(points[i])
  }
  keep.push(points[points.length - 1])
  return keep
}

const toLinear = (points) => `linear(${points.join(', ')})`

/** Springs, named for the job they do rather than their constants. */
const springs = {
  // Controls that must feel instant but still alive. Barely overshoots.
  snappy: { stiffness: 700, damping: 38 },
  // Critically damped — arriving somewhere, not showing off. Sheets, heights.
  smooth: { stiffness: 320, damping: 36 },
  // Deliberate overshoot. Pills, toasts, badges, selection.
  bouncy: { stiffness: 520, damping: 22 },
  // The most expressive step, for entrances that should feel delighted.
  playful: { stiffness: 420, damping: 16 },
}

/** Named curves sampled straight from easing-utils. */
const curves = {
  back: easings.easeOutBack,
  elastic: easings.easeOutElastic,
  bounce: easings.easeOutBounce,
  expo: easings.easeOutExpo,
}

const lines = []
const meta = []

for (const [name, cfg] of Object.entries(springs)) {
  const { raw, durationMs } = simulateSpring(cfg)
  const points = prune(resample(raw, 90))
  lines.push(`  --may-spring-${name}: ${toLinear(points)};`)
  lines.push(`  --may-spring-${name}-duration: ${durationMs}ms;`)
  meta.push({ name, ...cfg, durationMs, stops: points.length })
}

for (const [name, fn] of Object.entries(curves)) {
  const points = prune(
    Array.from({ length: 61 }, (_, i) => r(fn(i / 60))).map((v, i, a) =>
      i === 0 ? 0 : i === a.length - 1 ? 1 : v,
    ),
  )
  lines.push(`  --may-ease-${name}: ${toLinear(points)};`)
  meta.push({ name: `ease-${name}`, source: 'easing-utils', stops: points.length })
}

const css = `/**
 * GENERATED by scripts/gen-springs.mjs — do not edit.
 *
 * Real spring physics expressed as CSS \`linear()\` easings, so every spring in
 * May UI runs on the compositor with no runtime JavaScript. Regenerate with
 * \`npm run gen:springs\`.
 */

:root {
${lines.join('\n')}

  /* Fixed curves. The sheet curve is iOS's own presentation timing. */
  --may-ease-sheet: cubic-bezier(0.32, 0.72, 0, 1);
  --may-ease-standard: cubic-bezier(0.25, 0.1, 0.25, 1);
  --may-ease-out: cubic-bezier(0, 0, 0.2, 1);

  /* Durations. Named for intent; the springs carry their own above. */
  --may-duration-instant: 80ms;   /* press-down: must beat the eye           */
  --may-duration-fast: 150ms;
  --may-duration-settle: 340ms;   /* "200ms is too abrupt, 500ms feels heavy" */
  --may-duration-sheet-in: 500ms;
  --may-duration-sheet-out: 300ms;
  --may-duration-follow: 90ms;    /* finger-tracking, linear                  */
}

/*
 * Fallback for browsers without \`linear()\` (pre Chrome 113 / Safari 17.2 /
 * Firefox 112). They lose the overshoot but keep sensible motion.
 */
@supports not (animation-timing-function: linear(0, 1)) {
  :root {
    --may-spring-snappy: cubic-bezier(0.2, 0, 0.2, 1);
    --may-spring-smooth: cubic-bezier(0.32, 0.72, 0, 1);
    --may-spring-bouncy: cubic-bezier(0.34, 1.4, 0.64, 1);
    --may-spring-playful: cubic-bezier(0.34, 1.56, 0.64, 1);
    --may-ease-back: cubic-bezier(0.34, 1.56, 0.64, 1);
    --may-ease-elastic: cubic-bezier(0.34, 1.56, 0.64, 1);
    --may-ease-bounce: cubic-bezier(0.34, 1.56, 0.64, 1);
    --may-ease-expo: cubic-bezier(0.16, 1, 0.3, 1);
  }
}
`

writeFileSync(resolve(here, '../src/styles/motion.css'), css)
console.table(meta)
console.log(`\nwrote src/styles/motion.css (${css.length} bytes)`)
